defaults:
	# resize the ingredients and recipes, uses directory mode
	./scaler -d ingredientsOriginal 4 ingredientsIcons
	./scaler -d foodRecipeOriginal  3 foodRecipeManagerIcon
	./scaler -d foodRecipeOriginal  2 foodRecipeCardIcon

	# resize the icons, all must be done individually
	./scaler iconsOrigional/discordIcon.png 2 iconsDisplay/discordIcon.png
	./scaler iconsOrigional/kofiRound.png   3 iconsDisplay/kofiRound.png
	./scaler iconsOrigional/paimonSpoop.png 2 iconsDisplay/paimonSpoop.png
