defaults:
	# resize the ingredients and recipes, uses directory mode
	./scaler -d ingredientsOrigional 4 ingredientsIcons
	./scaler -d foodRecipeOrigional  3 foodRecipeManagerIcon
	./scaler -d foodRecipeOrigional  2 foodRecipeCardIcon

	# resize the icons, all must be done individually
	./scaler iconsOrigional/discordIcon.png 2 iconsDisplay/discordIcon.png
	./scaler iconsOrigional/kofiRound.png   3 iconsDisplay/kofiRound.png
	./scaler iconsOrigional/paimonSpoop.png 2 iconsDisplay/paimonSpoop.png