defaults:
	# resize the ingredients and recipes, uses directory mode
	./scaler -d ingredientsOriginal 4 ingredientsIcons

	./scaler -d foodRecipeOriginal  3 foodRecipeManagerIcon
	./scaler -d foodRecipeOriginal  2 foodRecipeCardIcon

	./scaler -d alchemyRecipeOriginal  3 alchemyRecipeManagerIcon
	./scaler -d alchemyRecipeOriginal  2 alchemyRecipeCardIcon
