export const RAW_INGREDIENTS = {
    rawIngredients: [
        {
            name: "Almond",
            src: "./images/ingredients/almond.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Apple",
            src: "./images/ingredients/apple.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Bamboo Shoot",
            src: "./images/ingredients/bambooShoot.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Berry",
            src: "./images/ingredients/berry.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Bird Egg",
            src: "./images/ingredients/birdEgg.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Cabbage",
            src: "./images/ingredients/cabbage.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Calla Lily",
            src: "./images/ingredients/callaLily.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Carrot",
            src: "./images/ingredients/carrot.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Chilled Meat",
            src: "./images/ingredients/chilledMeat.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Crab",
            src: "./images/ingredients/crab.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Fowl",
            src: "./images/ingredients/fowl.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Horsetail",
            src: "./images/ingredients/horsetail.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Jueyun Chili",
            src: "./images/ingredients/jueyunChili.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Lavender Melon",
            src: "./images/ingredients/lavenderMelon.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Lotus Head",
            src: "./images/ingredients/lotusHead.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Matsutake",
            src: "./images/ingredients/matsutake.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Mint",
            src: "./images/ingredients/mint.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Mushroom",
            src: "./images/ingredients/mushroom.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Onion",
            src: "./images/ingredients/onion.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Pepper",
            src: "./images/ingredients/pepper.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Pinecone",
            src: "./images/ingredients/pinecone.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Potato",
            src: "./images/ingredients/potato.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Qingxin",
            src: "./images/ingredients/qingxin.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Radish",
            src: "./images/ingredients/radish.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Rice",
            src: "./images/ingredients/rice.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Sakura Bloom",
            src: "./images/ingredients/sakuraBloom.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Salt",
            src: "./images/ingredients/salt.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Seagrass",
            src: "./images/ingredients/seagrass.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Shrimp Meat",
            src: "./images/ingredients/shrimpMeat.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Small Lamp Grass",
            src: "./images/ingredients/smallLampGrass.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Snapdragon",
            src: "./images/ingredients/snapdragon.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Sunsettia",
            src: "./images/ingredients/sunsettia.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Sweet Flower",
            src: "./images/ingredients/sweetFlower.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Tofu",
            src: "./images/ingredients/tofu.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Tomato",
            src: "./images/ingredients/tomato.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Unagi Meat",
            src: "./images/ingredients/unagiMeat.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Violetgrass",
            src: "./images/ingredients/violetgrass.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Wheat",
            src: "./images/ingredients/wheat.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Milk",
            src: "./images/ingredients/milk.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Fish",
            src: "./images/ingredients/fish.png",
            rarity: 1,
            obtainedBy: "forage",
        }
    ]
}