export const RAW_INGREDIENTS = {
    rawIngredients: [
        {
            name: "Almond",
            src: "./images/ingredientsIcons/almond.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Apple",
            src: "./images/ingredientsIcons/apple.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Bamboo Shoot",
            src: "./images/ingredientsIcons/bambooShoot.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Berry",
            src: "./images/ingredientsIcons/berry.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Bird Egg",
            src: "./images/ingredientsIcons/birdEgg.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Cabbage",
            src: "./images/ingredientsIcons/cabbage.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Calla Lily",
            src: "./images/ingredientsIcons/callaLily.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Carrot",
            src: "./images/ingredientsIcons/carrot.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Chilled Meat",
            src: "./images/ingredientsIcons/chilledMeat.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Crab",
            src: "./images/ingredientsIcons/crab.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Fowl",
            src: "./images/ingredientsIcons/fowl.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Horsetail",
            src: "./images/ingredientsIcons/horsetail.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Jueyun Chili",
            src: "./images/ingredientsIcons/jueyunChili.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Lavender Melon",
            src: "./images/ingredientsIcons/lavenderMelon.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Lotus Head",
            src: "./images/ingredientsIcons/lotusHead.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Matsutake",
            src: "./images/ingredientsIcons/matsutake.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Mint",
            src: "./images/ingredientsIcons/mint.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Mushroom",
            src: "./images/ingredientsIcons/mushroom.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Onion",
            src: "./images/ingredientsIcons/onion.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Pepper",
            src: "./images/ingredientsIcons/pepper.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Pinecone",
            src: "./images/ingredientsIcons/pinecone.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Potato",
            src: "./images/ingredientsIcons/potato.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Qingxin",
            src: "./images/ingredientsIcons/qingxin.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Radish",
            src: "./images/ingredientsIcons/radish.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Rice",
            src: "./images/ingredientsIcons/rice.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Sakura Bloom",
            src: "./images/ingredientsIcons/sakuraBloom.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Salt",
            src: "./images/ingredientsIcons/salt.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Seagrass",
            src: "./images/ingredientsIcons/seagrass.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Shrimp Meat",
            src: "./images/ingredientsIcons/shrimpMeat.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Small Lamp Grass",
            src: "./images/ingredientsIcons/smallLampGrass.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Snapdragon",
            src: "./images/ingredientsIcons/snapdragon.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Sunsettia",
            src: "./images/ingredientsIcons/sunsettia.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Sweet Flower",
            src: "./images/ingredientsIcons/sweetFlower.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Tofu",
            src: "./images/ingredientsIcons/tofu.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Tomato",
            src: "./images/ingredientsIcons/tomato.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Unagi Meat",
            src: "./images/ingredientsIcons/unagiMeat.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Violetgrass",
            src: "./images/ingredientsIcons/violetgrass.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Wheat",
            src: "./images/ingredientsIcons/wheat.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Milk",
            src: "./images/ingredientsIcons/milk.png",
            rarity: 1,
            obtainedBy: "shop",
        },
        {
            name: "Fish",
            src: "./images/ingredientsIcons/fish.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Amythest Lump",
            src: "./images/ingredientsIcons/amythestLump.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Butterfly Wings",
            src: "./images/ingredientsIcons/butterflyWings.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Crystal Chunk",
            src: "./images/ingredientsIcons/crystalChunk.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Crystal Core",
            src: "./images/ingredientsIcons/crystalCore.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Dead Ley Line Leaves",
            src: "./images/ingredientsIcons/deadLeyLineLeaves.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Electro Crystal",
            src: "./images/ingredientsIcons/electroCrystal.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Flaming Flower Stamen",
            src: "./images/ingredientsIcons/flamingFlowerStamen.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Frog",
            src: "./images/ingredientsIcons/frog.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Lizard Tail",
            src: "./images/ingredientsIcons/lizardTail.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Luminscent Spine",
            src: "./images/ingredientsIcons/luminescentSpine.png",
            rarity: 1,
            obtainedBy: "forage",
        },
        {
            name: "Mist Flower Corolla",
            src: "./images/ingredientsIcons/mistFlowerCorolla.png",
            rarity: 1,
            obtainedBy: "forage",
        }
    ]
}